app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'api/v1'], function () {
	Route::resource("baskets", "BasketController", [
		'only' => ['index', 'store', 'show', 'update', 'destroy']
	]);

	Route::resource("baskets.items", "ItemController", [
		'only' => ['store', 'destroy']
	]);
});
Route::get('/', function () {
	return View::make('docs.api.v1.index');
});

app/Base.php
<?php
/**
 * Created by PhpStorm.
 * User: kolyabres
 * Date: 27.05.16
 * Time: 14:08
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class Base extends Model
{
	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'created_at', 'updated_at',
	];

}

app/Basket.php
<?php

namespace App;


class Basket extends Base
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name', 'max',
	];


	/**
	 * Get the basket items
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function items()
	{
		return $this->hasMany('App\Item');
	}

	public function addItemsFromRequest($items)
	{
		$items_obj = [];
		foreach ($items as $item)
			$items_obj[] = new Item($item);
		$this->items()->saveMany($items_obj);
	}


}

app/FruitResponse.php
<?php
/**
 * Created by PhpStorm.
 * User: kolyabres
 * Date: 02.06.16
 * Time: 14:28
 */

namespace App;


use Illuminate\Http\Response;
use Illuminate\Support\Facades\Input;


class FruitResponse extends Response
{
	public static function makeResponse($body, $message = '', $code = 200)
	{
		$response = [
			'body' => $body,
			'message' => $message,
			'code' => $code
		];


		switch (Input::get('format', 'json')) {
			case 'json': {
				return response()->json($response, $code);
			}
		}
	}
}

app/FruitValidator.php
<?php
/**
 * Created by PhpStorm.
 * User: kolyabres
 * Date: 27.05.16
 * Time: 14:57
 */

namespace App;

use  Validator;

class FruitValidator
{


	public static function validateBasketWeight($weight, $items)
	{
		$sum = 0;
		foreach ($items as $item)
			$sum += $item['weight'];
		return ($weight - $sum) >= 0;

	}
}

app/Item.php
<?php

namespace App;



class Item extends Base
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'user_id', 'type', 'weight',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'created_at', 'updated_at','basket_id',
	];

	/**
	 * Get the basket that contains the item
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function basket()
	{
		return $this->belongsTo('App\Basket');
	}
}

app/Http/Controllers/BasketController.php
<?php namespace App\Http\Controllers;

use App\FruitValidator;
use App\FruitResponse;
use App\Http\Requests\StoreBasketRequest;
use App\Http\Requests\UpdateBasketRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Basket;
use App\Item;
use Illuminate\Http\Request;

use Validator;


class BasketController extends Controller
{

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$baskets = Basket::orderBy('id', 'desc')->paginate(10);

		return FruitResponse::makeResponse($baskets);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(StoreBasketRequest $request)
	{

		if (count($items = $request->input('items')))
			if (!FruitValidator::validateBasketWeight($request->input('max'), $items)) {
				return  FruitResponse::makeResponse([], 'Items too heavy.', 400);
			}

		$basket = new Basket($request->only('name', 'max'));
		$basket->save();

		if (count($items)) {
			$basket->addItemsFromRequest($items);
		}
		$basket['items'] = $basket->items()->getEager();
		return FruitResponse::makeResponse($basket, 'Basket created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function show($id)
	{
		$basket = Basket::with('items')->findOrFail($id);
		return FruitResponse::makeResponse($basket);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(UpdateBasketRequest $request, $id)
	{
		$basket = Basket::with('items')->findOrFail($id);

		$basket->update([
			'name' => $request->input("name")
		]);
		return FruitResponse::makeResponse($basket, 'Basket updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$basket = Basket::findOrFail($id);
		$basket->delete();
		return FruitResponse::makeResponse([], 'Basket deleted successfully.');
	}

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;


class Controller extends BaseController
{
	use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;

}

app/Http/Controllers/ItemController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Item;
use App\Basket;

use Illuminate\Http\Request;

use App\FruitValidator;
use App\FruitResponse;

use App\Http\Requests\StoreItemRequest;

class ItemController extends Controller
{
	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @param int $basket_id
	 * @return Response
	 */
	public function store(StoreItemRequest $request, $basket_id)
	{
		$basket = Basket::with('items')->findOrFail($basket_id);
		$items = $request->input('items');

		if (!count($items))
			return FruitResponse::makeResponse([], 'Bad request.', 400);

		if (!FruitValidator::validateBasketWeight($basket->max, array_merge($basket->items()->getEager()->toArray(), $items)))
			return  FruitResponse::makeResponse([], 'Items too heavy.', 400);


		$basket->addItemsFromRequest($items);

		$basket['items'] = $basket->items()->getEager();
		return FruitResponse::makeResponse($basket, 'Items added successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function destroy($basket_id, $id)
	{
		$item = Item::findOrFail($id);
		$item->delete();

		return FruitResponse::makeResponse([], 'Item deleted successfully.');
	}

}

resources/views/baskets/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Baskets / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('baskets.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('max')) has-error @endif">
                       <label for="max-field">Max</label>
                    <input type="text" id="max-field" name="max" class="form-control" value="{{ old("max") }}"/>
                       @if($errors->has("max"))
                        <span class="help-block">{{ $errors->first("max") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('baskets.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/baskets/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Baskets / Edit #{{$basket->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('baskets.update', $basket->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ $basket->name }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('max')) has-error @endif">
                       <label for="max-field">Max</label>
                    <input type="text" id="max-field" name="max" class="form-control" value="{{ $basket->max }}"/>
                       @if($errors->has("max"))
                        <span class="help-block">{{ $errors->first("max") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('baskets.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/baskets/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Baskets
            <a class="btn btn-success pull-right" href="{{ route('baskets.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($baskets->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                        <th>MAX</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($baskets as $basket)
                            <tr>
                                <td>{{$basket->id}}</td>
                                <td>{{$basket->name}}</td>
                    <td>{{$basket->max}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('baskets.show', $basket->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('baskets.edit', $basket->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('baskets.destroy', $basket->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $baskets->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/baskets/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Baskets / Show #{{$basket->id}}</h1>
        <form action="{{ route('baskets.destroy', $basket->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('baskets.edit', $basket->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$basket->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="max">MAX</label>
                     <p class="form-control-static">{{$basket->max}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('baskets.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection

resources/views/docs/api/v1/index.blade.php
@extends('layouts.docs.api.v1.default')

resources/views/error.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <p>There were some problems with your input.</p>
        <ul>
            @foreach ($errors->all() as $error)
                <li><i class="glyphicon glyphicon-remove"></i> {{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/docs/api/v1/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>FRUIT BASKET API DOCS</title>
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="/assets/docs/api.v1/css/normalize.min.css">
<link rel="stylesheet" href="/assets/docs/api.v1/css/main.css">
<link rel="stylesheet" href="/assets/docs/api.v1/css/prettify.css">
<link rel="stylesheet" href="/assets/docs/api.v1/css/f2m2-grid.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="//code.jquery.com/ui/1.10.2/jquery-ui.min.js"></script>
<script src="/assets/docs/api.v1/js/prettify.js"></script>
<script src="/assets/docs/api.v1/js/waypoints.min.js"></script>
<script src="/assets/docs/api.v1/js/highlight.js"></script>
<script src="/assets/docs/api.v1/js/main.js"></script>

resources/views/includes/docs/api/v1/introduction.blade.php
                        <a href="#" class="waypoint" name="introduction"></a>
                         <h1>Introduction</h1>
                        <p>This RESTful JSON API uses HTTP GET, POST, PUT, DELETE Requests to communicate with the System.</p>

                        <p>HTTP/1.1 Status Codes:</p>
                        <div>
                            <ul class="three-col-special">
                                <li>200  OK</li>
                                <li>201  Created</li>
                                <li>202  Accepted</li>
                                <li>204  No Content</li>
                                <li>301  Moved Permanently</li>
                                <li>302  Found</li>
                                <li>303  See Other</li>
                                <li>304  Not Modified</li>
                                <li>400  Bad Request</li>
                                <li>401  Unauthorized</li>
                                <li>402  Payment Required</li>
                                <li>403  Forbidden</li>
                                <li>404  Not Found</li>
                                <li>405  Method Not Allowed</li>
                                <li>406  Not Acceptable</li>
                                <li>408  Request Time-out</li>
                                <li>409  Conflict</li>
                                <li>410  Gone</li>
                                <li>411  Length Required</li>
                                <li>412  Precondition Failed</li>
                                <li>414  Request-URI Too Large</li>
                                <li>415  Unsupported Media Type</li>
                                <li>416  Requested range not satisfiable</li>
                                <li>500  Internal Server Error</li>
                                <li>501  Not Implemented</li>
                                <li>502  Bad Gateway</li>
                                <li>505  HTTP Version not supported</li>
                            </ul>
                        </div>
                    </BR></BR></BR>
                        <p>JSON response</p>
                        <pre class="prettyprint linenums">
{
  "code": 200,
  "message": "",
  "body": {
  }
}
                     </pre>



                    <p>Collection Response (HTTP/1.1 STATUS CODES 2xx)</p>
                    <pre class="prettyprint linenums">
{
  "code": 200,
   "body": {

      "items" : {
        "per_page" : 15,
        "from" : 1,
        "data" : [
          {
            "id" : 1,
          }
        ],
        "total" : 1,
        "current_page" : 1,
        "last_page" : 1,
        "to" : 1
      }
   }
}
                    </pre>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Starter Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        @yield('header')
        @yield('content')
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->

</body>
</html>